stages:
  preprocess:
    cmd: python preprocess.py
    deps:
      - preprocess.py
      - data/titanic_raw.csv
    outs:
      - data/train.csv
      - data/test.csv

  train:
    cmd: python train.py
    deps:
      - train.py
      - data/train.csv

  tune:
    cmd: python tune.py
    deps:
      - tune.py
      - data/train.csv
